image: node:6.9.4

pipelines:
  custom:
     test-repository:
       - step:
           caches:
             - node
           script:
             - node --version
             - npm --version
             - npm install -g ts-node typescript
             - npm install --unsafe-perm
             - npm test
     deployment-to-prod:
       - step:
           caches:
             - composer
           script:
             - node --version
             - npm --version
             - npm install -g ts-node typescript
             - npm install --unsafe-perm
             - npm run build-prod
#  branches:
#      master:
#        - step:
#            caches:
#              - node
#            script:
#              - node --version
#              - npm --version
#              - npm install -g ts-node typescript
#              - npm install --unsafe-perm